### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'n'

### ISSUE THREAD

**Issue by rooffall** [mearashadowfax/GuardianVPN#8]
Hello, there is a bug in the new version due to the language pack.
When choosing OpenVPN or WG:

ERROR:telegram.ext._application:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/venv/env/lib/python3.11/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/root/venv/env/lib/python3.11/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/dev/GuardianVPN-main/modules/config_functions.py", line 52, in button_callback
    with open(language_file_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'n'

**Comment by mearashadowfax** [comment]
Thank you for opening the issue. Got it, looks like using the `await get_language(update, context)` approach might be a good idea. I'll update the code and let you know.

**Comment by mearashadowfax** [comment]
Hi @rooffall,

We've identified and fixed the problem related to the language pack that was causing the error you encountered.

The issue has been resolved by implementing the `await get_language(update, context)` approach in our code. You should no longer experience the 'FileNotFoundError' issue.

Once again, thanks for bringing this to our attention.
